import { Inter, Lalezar, Montserrat } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'
import { ThemeProvider } from '@/context/ThemeContext';


const montserrat = Montserrat({ subsets: ['latin'], weight: ['400', '900', '100', '700']});
const lalezar = Lalezar({ subsets: ['arabic'], weight: ['400'] })

export const metadata = {
  title: 'Hexshop',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ThemeProvider>

        <div className="containers">
          <Navbar />
            {children}
          <Footer />
        </div>
        
      </ThemeProvider>
      </body>
    </html>
  )
}
